# Pueblos plugin by RonanCraft! (Join my Public Server mc.RonanCraft.net) #
# Need help? go to https://ronancraft.net/discord! #

Language-File: 'en.yml'
DisableUpdater: false
Claim:
  Item: 'golden_shovel'
  Limit: 3
  MaxSize: 256