main: me.RonanCraft.BetterClaims.BetterClaims
version: ${project.version}
website: "https://ronancraft.net"
description: "Create protected regions of land quickly"
name: BetterClaims
author: RonanCraft
softdepend:
    - Vault
    - PlaceholderAPI
api-version: '1.13'

commands:
    claim:
        aliases: [bclaim, claims, bclaims, betterclaim, betterclaims]
        description: 'Main claim command'

permissions:
    betterclaims.use:
        description: 'Use the plugin'
        default: true
    betterclaims.reload:
        description: 'Reload the plugin'
        default: op
    betterclaims.request:
        description: 'Request to join a claim'
        default: true
    betterclaims.item:
        description: 'Grab a copy of the claim creation item'
        default: op
    betterclaims.teleport:
        description: 'Teleport to a claim via the gui'
        default: op
    betterclaims.admin.claim:
        description: 'Create & Edit admin claims, toggled with "/claims adminclaim"'
        default: op
    betterclaims.admin.convert:
        description: 'Convert claims from other plugins using "/claims convert <plugin>"'
        default: op
    betterclaims.admin.override:
        description: 'Override all claims when executing "/claims override"'
        default: op