main: me.RonanCraft.Pueblos.Pueblos
version: '1.1.0'
name: Pueblos
author: RonanCraft
softdepend:
    - Vault
    - PlaceholderAPI
api-version: '1.13'

commands:
    pueblos:
        aliases: [pueblo, claim, claims, town, towns]
        description: Main pueblos command

permissions:
    pueblos.use:
        description: Use the plugin
        default: true
    pueblos.reload:
        description: Reload the plugin
        default: op
    pueblos.request:
        description: Request to join a claim
        default: true
    pueblos.admin.claim:
        description: Create & Edit admin claims, toggled with "/pueblos adminclaim"
        default: op
    pueblos.admin.override:
        description: Override all claims when executing "/peublos override"
        default: op