main: me.RonanCraft.BetterClaims.BetterClaims
version: ${project.version}
website: "https://ronancraft.net"
description: "Create protected regions of land quickly"
name: BetterClaims
author: RonanCraft
softdepend:
    - Vault
    - PlaceholderAPI
api-version: '1.13'

commands:
    pueblos:
        aliases: [pueblo, claim, claims]
        description: 'Main pueblos command'

permissions:
    pueblos.use:
        description: 'Use the plugin'
        default: true
    pueblos.reload:
        description: 'Reload the plugin'
        default: op
    pueblos.request:
        description: 'Request to join a claim'
        default: true
    pueblos.item:
        description: 'Grab a copy of the claim creation item'
        default: op
    pueblos.teleport:
        description: 'Teleport to a claim via the gui'
        default: op
    pueblos.admin.claim:
        description: 'Create & Edit admin claims, toggled with "/pueblos adminclaim"'
        default: op
    pueblos.admin.convert:
        description: 'Convert claims from other plugins using "/pueblos convert <plugin>"'
        default: op
    pueblos.admin.override:
        description: 'Override all claims when executing "/peublos override"'
        default: op